import { useRef, useState } from "react";
import PdfDownloadButton from "../components/PdfDownloadButton";
import TransactionTable from "../components/TransactionTable";
import api from "../services/api";

const now = new Date();

const ReportsPage = () => {
  const [month, setMonth] = useState(now.getMonth() + 1);
  const [year, setYear] = useState(now.getFullYear());
  const [report, setReport] = useState(null);
  const [error, setError] = useState("");
  const reportRef = useRef(null);

  const fetchReport = async () => {
    setError("");
    try {
      const { data } = await api.get(`/reports/monthly?month=${month}&year=${year}`);
      setReport(data);
    } catch (apiError) {
      setError(apiError.response?.data?.message || "Could not fetch report.");
    }
  };

  return (
    <section className="space-y-5">
      <div className="temple-card grid gap-3 p-4 sm:grid-cols-4">
        <label className="text-sm">
          Month
          <input
            type="number"
            min="1"
            max="12"
            className="temple-input mt-1"
            value={month}
            onChange={(e) => setMonth(Number(e.target.value))}
          />
        </label>
        <label className="text-sm">
          Year
          <input
            type="number"
            min="2000"
            max="3000"
            className="temple-input mt-1"
            value={year}
            onChange={(e) => setYear(Number(e.target.value))}
          />
        </label>
        <div className="flex items-end">
          <button type="button" onClick={fetchReport} className="temple-button w-full">
            Generate Report
          </button>
        </div>
        <div className="flex items-end">{report && <PdfDownloadButton targetRef={reportRef} fileName={`temple-report-${year}-${month}.pdf`} />}</div>
      </div>

      {error && <p className="rounded-lg bg-red-100 p-2 text-red-800">{error}</p>}

      {report && (
        <div ref={reportRef} className="space-y-4 bg-white p-4 text-black rounded-lg">
          <div className="border-b pb-3">
            <h2 className="font-heading text-2xl text-[#5B1E1E]">Temple Monthly Inventory Report</h2>
            <p>
              Month: {report.month}/{report.year}
            </p>
          </div>

          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            <div className="rounded border p-3">
              <p className="text-xs text-gray-600">Opening Sarees</p>
              <p className="text-2xl font-semibold">{report.openingStock.sarees}</p>
            </div>
            <div className="rounded border p-3">
              <p className="text-xs text-gray-600">Opening Panchas</p>
              <p className="text-2xl font-semibold">{report.openingStock.panchas}</p>
            </div>
            <div className="rounded border p-3">
              <p className="text-xs text-gray-600">Closing Sarees</p>
              <p className="text-2xl font-semibold">{report.closingStock.sarees}</p>
            </div>
            <div className="rounded border p-3">
              <p className="text-xs text-gray-600">Closing Panchas</p>
              <p className="text-2xl font-semibold">{report.closingStock.panchas}</p>
            </div>
          </div>

          <div className="grid gap-3 sm:grid-cols-2">
            <div className="rounded border p-3">
              <h3 className="font-semibold">Stock Added</h3>
              <p>Sarees: {report.stockAdded.sarees}</p>
              <p>Panchas: {report.stockAdded.panchas}</p>
            </div>
            <div className="rounded border p-3">
              <h3 className="font-semibold">Stock Distributed</h3>
              <p>Sarees: {report.stockDistributed.sarees}</p>
              <p>Panchas: {report.stockDistributed.panchas}</p>
            </div>
          </div>

          <div className="rounded border p-3">
            <h3 className="font-semibold">Stock Adjustments (Reset/Clear)</h3>
            <p>Sarees: {report.stockAdjustments?.sarees ?? 0}</p>
            <p>Panchas: {report.stockAdjustments?.panchas ?? 0}</p>
          </div>

          <h3 className="font-semibold">Transaction History</h3>
          <TransactionTable items={report.transactionHistory} plain />

          <p className="text-xs text-gray-600">Generated by Temple Inventory Management System</p>
        </div>
      )}
    </section>
  );
};

export default ReportsPage;
